### ISSUE TITLE
Разработка релиза RelayBypass для версии double mimic

### ISSUE THREAD

**Issue by D1sconnected** [D1sconnected/RelayBypass#23]
## Какая цель у данной задачи?

Было решено разработать управление для новой гитарной педали на базе STM-32 и имеющегося кода `RelayBypass`, заодно подготовив наконец-то первый релиз.

Рабочее название педали `double mimic` - это двух-канальная версия `shape mimic`, мульти-эффекта на базе FV-1. 
Необходимо добавить функционал, которого еще нет в RelayBypass и придумать систему для конфигурации проекта под разные педали.

## Требуемый функционал

* [ ] Портировать имеющийся функционал на новую плату `double mimic` `revA`
* [ ] Реализовать систему для конфигурации проекта
* [ ] Реализовать переключение пресетов FV-1
* [ ] Реализовать переключение I2C флешек FV-1
* [ ] Реализовать сохранение параметров на SPI-флешку
* [ ] Реализовать Tap Temo #18

## Что на выходе?

* [ ] Подготовленный релиз `RelayBypass` для платы `double mimic`
